version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/data/postgres
    env_file:
      - .env

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5480:80"
    volumes:
      - pgadmin:/root/.pgadmin
    env_file:
      - .env
    

volumes:
  pgdata:
    driver: local
  pgadmin:
    driver: local    